### ISSUE TITLE
Go To File (M-t) Doesn't Work (At Least In Ubuntu)

### ISSUE THREAD

**Issue by jackowayed** [defunkt/textmate.el#2]
Not sure if it works for you, but for me (GNU Emacs on Ubuntu Intrepid Ibex), M-t fails.

It seems to append the entire path to my current folder. Example:

I'm editing some file in ~ (/home/daniel/), and I want to go change my .emacs file. I would hit M-t, start typing ".emacs", hit enter on .emacs, and it would bring me a new buffer with path /home/daniel/home/daniel/.emacs. 

So it appends the _entire_ path rather than the relative path from where I'm starting. 

PS I love textmate.el (That's not a bug :) )

**Comment by anildigital** [comment]
jackowayed, checkout http://github.com/anildigital/textmate.el/tree.. I had added a patch for this. http://github.com/anildigital/textmate.el/commit/59b7980fd567123d157f37f18e411d0eb54518a7

**Comment by defunkt** [comment]
Fixed in 0360f08c7f702d64a48723b88798474bef2ba506

**Comment by waed20107** [comment]
> http://github.com/anildigital/textmate.el/tree

https://youtube.com/user/as0566s
