### ISSUE TITLE
textmate-goto-symbol uses only symbols defined when the file was first opened

### ISSUE THREAD

**Issue by oandregal** [defunkt/textmate.el#25]
I'm experiencing a weird behaviour: when using textmate-goto-symbol, it finds all symbols defined when I first opened the file (for example, functions in a python file). But, if I add new functions to that file, textmate-goto-symbol doesn't find them until I close and reopen the file again.

Is there a convenient way to automatize this as much as possible? A good start would be having a function to recalculate the symbols (like textmate-symbols-recalculate or something).

**Comment by carlos-wong** [comment]
I think it would be better make a function as reopen-file ....

On Fri, Oct 18, 2013 at 4:03 PM, Andrés Maneiro notifications@github.comwrote:

> I'm experiencing a weird behaviour: when using textmate-goto-symbol, it
> finds all symbols defined when I first opened the file (for example,
> functions in a python file). But, if I add new functions to that file,
> textmate-goto-symbol doesn't find them until I close and reopen the file
> again.
> 
> Is there a convenient way to automatize this as much as possible? A good
> start would be having a function to recalculate the symbols (like
> textmate-symbols-recalculate or something).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/defunkt/textmate.el/issues/25
> .

## 

## 

Name:         黄怀贤
Mobile：  +86 15012704713
