### ISSUE TITLE
textmate-goto-file shows full paths

### ISSUE THREAD

**Issue by ctrochalakis** [defunkt/textmate.el#3]
Hello,
When using textmate-goto-file with ido mode the full paths are showed for _every_ file avaliable, this is not what happens with ido-find-file where the full path is shown only once.

textmate:
Find: {<full_path>/a | <full_path>/b |.... }
ido find-file:
Find file: <full_path>/{a | b | c}

**Comment by defunkt** [comment]
Are you using the latest version? I don't see full paths: http://skitch.com/defunkt/nyj9i

**Comment by ctrochalakis** [comment]
Hmm, that's strange. Yes, I am using the latest textmate version with GNU Emacs 23.1.50.1
http://picturepush.com/public/2291324

**Comment by defunkt** [comment]
Can someone run this code and let me know what you get:

```
(textmate-cached-project-files (textmate-project-root))
```

You can run this by placing that sexp into the comment of a Python or Ruby file (for example) in your project, placing your cursor after the last `)`, then typing `M-x eval-last-sexp`. This'll execute the code and print the result to the `*Messages*` buffer.

Example:

![](http://img.skitch.com/20100518-cw42hp681g3eyumgm32qu71789.png)

**Comment by mkaito** [comment]
This is probably what causes bug #2, and the reason anil's patch works. Wonder whether removing the project-root component from all strings in the list would break it.

**Comment by mkaito** [comment]
I've fixed both #3 and #2 by doing the above. Sending a pull request to Mr Defunkt.

**Comment by defunkt** [comment]
Merged, thanks!
