### ISSUE TITLE
flymake errors and closing

### ISSUE THREAD

**Issue by selman** [defunkt/textmate.el#5]
http://gist.github.com/463664

configured my ~/emacs.d/init.el as this gist. without supplied patch if I use textmate-goto-file flymake errors and closing with same config rinari-find-file-in-project running without problem.

GNU Emacs 23.2.1 (i686-pc-linux-gnu, GTK+ Version 2.20.1) of 2010-05-08 on pidsley.hoetzel.info

**Comment by defunkt** [comment]
Can you try now? We just merged in some bugfixes.

**Comment by selman** [comment]
thanks a lot it's ok now.

**Comment by ghost** [comment]
![Uploading IMG_20210111_031147.jpg…]()
