### ISSUE TITLE
Some keybindings not working on Emacs Cocoa

### ISSUE THREAD

**Issue by henrymazza** [defunkt/textmate.el#6]
on command + option + [ it says: M-s-“ not defined

**Comment by bradwright** [comment]
I have this in my Emacs:

```
;; Free up the option key for special characters
(setq ns-alternate-modifier 'none)
(setq ns-command-modifier 'meta)
(setq ns-function-modifier 'super)
```

So fn+t is "find in project" etc. Obviously I have command bound to Meta.

**Comment by henrymazza** [comment]
Yeah! I love ⌘ as it is. Now in hindsight I see it doesn't belong here, it's probably an Emacs bug. Won't bother the people of textmate.el with this bug. Closing…
