### ISSUE TITLE
"GO TO FILE" cannot work with GNU Emacs 24 BRZ

### ISSUE THREAD

**Issue by seagle0128** [defunkt/textmate.el#9]
I am using BRZ GUN Emacs 24 and textmate. But "Go to File" cannot work. It prompts "($ was unexpected at this time." every time. I suppose the root cause is invalid _textmate-gf-exclude_.

**Comment by unknownnf** [comment]
My fork fixes the issue I think, some versions of grep don't like ' tricks.

**Comment by seagle0128** [comment]
Yes. Thanks! I think it's the root cause.
